name: Multi Job Workflow

on: 
  workflow_dispatch:

jobs:
    setup-dependencies:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Install Dependencies
              run: echo "Install .Net 8 Dependencies"

    build:
        runs-on: ubuntu-latest
        needs: setup dependencies
        steps:
            - name: Build .Net 8 API
              run: echo "Build .Net 8 API"

    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Test .Net 8 API
              run: echo "Test .Net 8 API"
